### ISSUE TITLE
Careful

### ISSUE THREAD

**Issue by AbleLincoln** [afairbarns/teacozy#4]
Be careful with the opacity style. Here you are using it to make the .main-content have an opacity of 0.9. I'm not sure what your intended goal was, but what this does was make everything in the .main-content (so nearly everything) be slightly less opaque. I think what you were going for was a slightly transparent background. In that case you should use background-color with RGBA values. The CSS would look like this:

`background-color: RGBA(0,0,0,0.9);`

You can read about RGBA [here](https://www.w3schools.com/css/css3_colors.asp).

https://github.com/afairbarns/teacozy/blob/master/resources/css/style.css#L51

**Comment by afairbarns** [comment]
It appeared from the redline/wireframe that the entire site page was to have an opacity of 0.9. However, looking again - it could be referencing the background. Thank You for pointing this out.
